parameters:
#    lia_form.example.class: Lia\Bundle\FormBundle\Example

services:
#    lia_form.example:
#        class: %lia_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
